version: '3.8'

services:
  nextcordbot:
    build: .
    container_name: bot
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: botdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
