version: '3.8'

services:
  nextcordbot:
    build: .
    container_name: nextcordbot
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
      - ollama
    ports:
      - "8080:8080"  # Adjust if needed
    volumes:
      - .:/app  # Mount current directory if necessary
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: botdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - OLLAMA_API_KEY=your_ollama_api_key_here
    ports:
      - "11434:11434"
    restart: unless-stopped
    volumes:
      - ollama-data:/ollama/data
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [compute, utility]

volumes:
  db-data:
  ollama-data:
