"""Describe your changes here

Revision ID: 1661e31df72d
Revises: 86199659cdae
Create Date: 2024-09-23 17:51:09.385752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1661e31df72d'
down_revision = '86199659cdae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
