"""Initial migration

Revision ID: 86199659cdae
Revises: 
Create Date: 2024-09-23 17:48:13.358401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86199659cdae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
